name: Docker automatic build and publish when changes in ET/containers/ directory

# Each directory ET/containers/<dir> maps to a container we may want to (re)build.

# Condition to trigger the workflow:
# - a push that pushes a commit to the 'main' branch in github that modifies anything inside the directory ET/containers/
on:
  push:
    branches:
      - main
    paths:
      - ET/containers/**
      - '!ET/**/README.md'

env:
  REGISTRY: ghcr.io

jobs:

  # JOB 1
  # Build a list with all directories inside ET/containers/ that have been modified (except for modifications in README files).
  build-list-of-changed-dirs:
    runs-on: ubuntu-latest 
    name: Build list of ET/containers/* directories with modified files

    steps:
      - name: Docker Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2

      # Get list of all files inside ET/containers/ (except for README.md files) that have been modified.
      # The output is a list available in steps.<this-step-id>.outputs.all_changed_files.
      # Each element of the list has the form ET/containers/<dir>/... where <dir> corresponds to a container we want to build.
      - name: Get list with all changed files
        id: changed-files
        uses: tj-actions/changed-files@v41.0.1
        with:
          files: |
            ET/containers/**
            !ET/**/README.md
          dir_names: "true"
          dir_names_exclude_current_dir: "true"

      - name: Build list with all changed dirs inside ET/containers/
        id: changed-dirs
        run: |
          echo "Parsing changed directories..."
          declare -A seen
          dirs=()
          for f in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$f was changed"
            d=$(echo "$f" | cut -d'/' -f3)
            if [[ -n "${seen[$d]}" ]]; then
              continue
            fi
            seen[$d]=1
            dirs+=("\"${d}\"")
          done
          CHANGED_DIRS=`echo "[${dirs[*]}]" | sed 's/ /,/g'`
          echo "Updated list of changed directories: $CHANGED_DIRS"
          # The following echo adds a variable container_list to the outputs of this step,
          # that then we will pass it to the output of the job.
          echo "changed_dirs=$CHANGED_DIRS" >> "$GITHUB_OUTPUT"

    outputs:
      changed_dirs: ${{ steps.changed-dirs.outputs.changed_dirs }}

  # Job 2
  # Build a new container for each directory in the output list of JOB 1
  build-and-push-containers:
    needs: build-list-of-changed-dirs
    if: needs.build-list-of-changed-dirs.outputs.changed_dirs != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers: ${{ fromJSON(needs.build-list-of-changed-dirs.outputs.changed_dirs) }}

    permissions:
      contents: read
      packages: write

    # The following steps will run for each element in matrix.containers.
    # This means that a container will be (re)build for each directory inside ET/containers/ that has modifications.
    steps:
      - name: Docker Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Detect git tag on HEAD
        id: git_tag
        run: |
          TAG=$(git tag --points-at HEAD | head -n 1)
          echo "Detected tag: $TAG"
          if [ -z "$TAG" ]; then
            echo "has_tag=false" >> $GITHUB_OUTPUT
          else
            echo "has_tag=true" >> $GITHUB_OUTPUT
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          fi

      - name: Compute short SHA of HEAD
        id: short_sha
        run: |
          echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Log in to the GH Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push ET ${{ matrix.containers }}
        id: build
        uses: docker/build-push-action@v5.1.0
        with:
          context: ET/containers/${{ matrix.containers }}
          file: ET/containers/${{ matrix.containers }}/Dockerfile
          push: true
          tags: |
            ${{ steps.git_tag.outputs.has_tag == 'false' && format('{0}/{1}/et-{2}:dev-{3}', env.REGISTRY, github.repository_owner, matrix.containers, steps.short_sha.outputs.short_sha) || '' }}
            ${{ steps.git_tag.outputs.has_tag == 'true' && format('{0}/{1}/et-{2}:{3}', env.REGISTRY, github.repository_owner, matrix.containers, steps.git_tag.outputs.tag) || '' }}
            ${{ steps.git_tag.outputs.has_tag == 'true' && !contains(steps.git_tag.outputs.tag, '-rc') && format('{0}/{1}/et-{2}:latest', env.REGISTRY, github.repository_owner, matrix.containers) || '' }}
          build-args: |
            BUILD_DATE=$(date +'%Y-%m-%dT%H:%M:%SZ')
